gen_moddeps.sh with ALLFIRMWARE="no": always include firmware for built-in modules
gentoo/genkernel pull request #54
Opened 2023-10-29 10:14 UTC by maciejsszmigiero

With the radeon module built-in into the kernel and ALLFIRMWARE="no" I get a black screen after boot due to missing GPU firmware.

The issue here is that built-in modules do not occur in the "modules.dep" file so they won't be caught by the dependency scanning loop in gen_dep_list().

They need to be manually added to the module list - do that unconditionally, since if a user wanted some module built-in into the kernel they definitely expect it to work properly at boot.

2023-10-29 10:18 UTC, thesamesam commented
@reagentoo

2023-10-30 07:46 UTC, reagentoo commented
> With the radeon module built-in into the kernel and ALLFIRMWARE="no" I get a black screen after boot due to missing GPU firmware.

1. What are the module name exactly?
2. Can you show all relevant variables from cfg file:
`cat /etc/genkernel.conf | grep -e FIRMWARE -e MODULES`

2023-10-30 10:15 UTC, maciejsszmigiero commented
> What are the module name exactly?

In this particular case is `radeon` but in principle it could be any built-in module that requires firmware, so a list hard-coded in genkernel wouldn't work very well.

> Can you show all relevant variables from cfg file.

Sure:
> FIRMWARE="yes"
> RAMDISKMODULES="no"

Rest of these variables are commented out (the default state in this config file).

2023-10-30 11:05 UTC, reagentoo commented
> > Can you show all relevant variables from cfg file.
>
> Sure:
> > FIRMWARE="yes"
> > RAMDISKMODULES="no"
> 
> Rest of these variables are commented out (the default state in this config file).

You can try to add this line:
```
AMODULES_DRM="radeon"
```

2023-10-30 11:09 UTC, maciejsszmigiero commented
> You can try to add this line:

At this point I could just manually add the relevant firmware files to `FIRMWARE_FILES`.

The whole point is to automatically detect the required minimum set of firmware files, so a user doesn't have to  manually configure this in genkernel.

2023-10-30 12:09 UTC, reagentoo commented
> The issue here is that built-in modules do not occur in the "modules.dep" file so they won't be caught by the dependency scanning loop in gen_dep_list().

I see. The inability to determine the dependencies of built-in modules worsens the picture...
Can you do the additional research:
```
mkdir test
depmod -a -o test
```
And check `test/lib/modules/*-gentoo-dist/modules.dep` for built-in modules.

2023-10-30 19:32 UTC, maciejsszmigiero commented
> And check `test/lib/modules/*-gentoo-dist/modules.dep` for built-in modules.

Can't find built-in modules in the above file.
It contains Just the external modules.

2023-10-31 07:37 UTC, reagentoo commented
@maciejsszmigiero do you have monolithic kernel? Can you please share this info:
```
ls -1hs /boot/ | grep "initramfs\|vmlinuz"
```

2023-10-31 09:24 UTC, maciejsszmigiero commented
> do you have monolithic kernel?

I have only drivers for basic machine hardware built-in into the kernel, rest are compiled as modules.

> (to show the sizes before and after your changes)

`.old` is before the change, and my kernel file is called `kernel`, not `vmlinuz`:
> 4,4M initramfs-6.5.8.img.old
> 5,2M initramfs-6.5.8.img
> 7,7M kernel-6.5.8

2023-10-31 10:28 UTC, reagentoo commented
> > You can try to add this line:
> 
> At this point I could just manually add the relevant firmware files to `FIRMWARE_FILES`.
> 
> The whole point is to automatically detect the required minimum set of firmware files, so a user doesn't have to manually configure this in genkernel.

I will approve of this PR. But excessive "manually configure in genkernel" by the user is not the reason.
The problem is precisely the inability to get the dependencies of built-in modules. Accordingly, there is no way to automatically add firmware from modules that are not in the `$MODULES_*` and `$AMODULES_*`.
So, please write commit description more relevant and remove mention about "black screen" and "radeon module".

With these changes, all firmwares will be automatically added to the image if the user builds a monolithic kernel:
```
$ equery s sys-kernel/linux-firmware
 * sys-kernel/linux-firmware-20231030
         Total files : 3786
         Total size  : 987.79 MiB

$ ls -1sh /var/cache/binpkgs/sys-kernel/linux-firmware | grep gpkg
447M linux-firmware-20231030-1.gpkg.tar
```

2023-10-31 11:17 UTC, reagentoo commented
> > do you have monolithic kernel?
> 
> I have only drivers for basic machine hardware built-in into the kernel, rest are compiled as modules.

BTW, why do you make built-in radeon module? You can modify AMODULES_DRM and radeon-firmwares will be in the initrd image even if radeon is not built-in.

2023-10-31 23:19 UTC, maciejsszmigiero commented
> In short: your issue case is not relevant to the current PR-modifications, but you can continue your work.
> So, please write commit description more relevant and remove mention about "black screen" and "radeon module".

To be clear, the part about `radeon` black screen wasn't meant as a blame, rather a description of the issue I hit.
But I have removed this part from the commit log, no problem.

> BTW, then why do you make built-in radeon module? You can modify AMODULES_DRM and radeon-firmwares will be in the initrd image even if radeon is not built-in.

I guess you mean "even if radeon *is* built-in" above.

I  use genkernel in the initramfs-only mode (`genkernel initramfs`), don't need any modules in the generated initramfs since I already have the modules necessary for booting built into the kernel.

2023-11-01 07:32 UTC, reagentoo commented
> To be clear, the part about radeon black screen wasn't meant as a blame, rather a description of the issue I hit.
But I have removed this part from the commit log, no problem.

Can you edit your commit according reviewed suggestions?

I see this commit as a workaround.
If a way to calculate built-in module dependencies was found, it would have to be reverted.
So, I would put this module in a `$AMODULES_DRM` variable anyway.

2023-11-01 08:28 UTC, maciejsszmigiero commented
> Can you edit your commit according reviewed suggestions?

So how?

> If a way to calculate built-in module dependencies was found, it would have to be reverted.

If a built-in module have a dependency on another module then this is handled by the kernel configuration tool (the one in kernel sources, not genkernel).
And this tool won't allow a module to be selected as built-in until all its dependencies are also selected as built-in.

> So, I would put this module in a `$AMODULES_DRM` variable anyway.

That I disagree with - having to do manual configuration isn't very user friendly.

The user has already decided they want this module built into their kernel and genkernel can easily detect this - that's essentially what this PR does.

There should be no need to manually edit any config.

2023-11-01 08:49 UTC, reagentoo commented
> > Can you edit your commit according reviewed suggestions?
> 
> So how?

See the commend for this diff.
https://github.com/gentoo/genkernel/pull/54/files#diff-1e5fead2f4ce499d3f346dcbe1d61df71f5fd25a734546c4aa000c3446899ff5R74-R76

> > If a way to calculate built-in module dependencies was found, it would have to be reverted.
> 
> If a built-in module have a dependency on another module then this is handled by the kernel configuration tool (the one in kernel sources, not genkernel). And this tool won't allow a module to be selected as built-in until all its dependencies are also selected as built-in.

I'm talking only about calculating dependencies specifically in genkernel. Since this affects the number of included firmwares. The user should be able to enable a minimum number of firmwares, knowing only the list of modules that are needed when loading. This commit could potentially include extra firmware in the image that is not needed when booting.

> I use genkernel in the initramfs-only mode (`genkernel initramfs`), don't need any modules in the generated initramfs since I already have the modules necessary for booting built into the kernel.

You refuse to include modules in the image, but at the same time you include firmware in the image...

2023-11-01 08:59 UTC, maciejsszmigiero commented
> See the commend for this diff.
https://github.com/gentoo/genkernel/pull/54/files#diff-1e5fead2f4ce499d3f346dcbe1d61df71f5fd25a734546c4aa000c3446899ff5R74-R76

Can't see any comment on this diff, do you mean "Always include firmware for built-in modules" comment in the change itself?

>  The user should be able to enable a minimum number of firmwares, knowing only the list of modules that are needed in boot time. 
>  This commit could potentially include extra firmware in the image that is not needed when booting.

The user has already configured what modules they need to boot - they set their kernel config accordingly.

> You refuse to include modules in the image, but at the same time you include firmware in the image...

initramfs is the only place firmware can be put into automatically.

Also, including modules in initramfs that would require configuring these modules in two places - in the kernel config and in genkernel.

If, however, a user has built everything as a module then this change doesn't bother them - it would simply be a NOP since there wouldn't be any built-in modules.
But it fixes a case that otherwise doesn't work currently.

2023-11-01 09:06 UTC, reagentoo commented
> Can't see any comment on this diff, do you mean "Always include firmware for built-in modules" comment in the change itself?

![изображение](https://github.com/gentoo/genkernel/assets/7188586/d48f0645-acd9-4eb9-8c49-f49f0557f046)

2023-11-01 09:18 UTC, maciejsszmigiero commented
Can't see it in GitHub - but it is marked as "Pending" in your screenshot so I guess you haven't posted (finalized) the review with this comment.

I think only then it will become visible for others.

2023-11-01 09:28 UTC, reagentoo requested changes

2023-11-01 09:28 UTC, reagentoo commented on gen_moddeps.sh
> +		cat "${moddir}/modules.builtin"
1. Please move these lines into place before `printf '%s\n' "${moddeplist[@]}"` (similar cat's sequence in ALLRAMDISKMODULES=y case).
2. And remove 4 lines above:
```
			cat "${moddir}/modules.builtin" \
				| xargs printf '%s:\n' \
				| grep -F "${rxargs[@]}"

```

2023-11-01 09:53 UTC, reagentoo commented
> initramfs is the only place firmware can be put into automatically.

I guess it is possible to automate the inclusion of firmware in the kernel for built-in modules.

2023-11-01 11:52 UTC, maciejsszmigiero commented on gen_moddeps.sh
> +		cat "${moddir}/modules.builtin"
Done.

2023-11-01 12:09 UTC, reagentoo commented
@thesamesam approved.

2024-01-27 22:39 UTC, maciejsszmigiero commented
@thesamesam can this be finally merged?
Thanks.

2024-02-02 09:33 UTC, reagentoo commented
Was moved to https://github.com/gentoo/genkernel/pull/57
Please test if possible.

2024-05-07 22:34 UTC, maciejsszmigiero commented
Obsoleted by #57.

2024-05-07 22:34 UTC, closed without merging